import Navbar from "@/components/layout/Navbar";
import { QueryProvider } from "@/lib/queryProvider";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"], // matches Figma usage
  variable: "--font-lato",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Anaespana Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable}>
      <body
        className={`${lato.variable} antialiased`}
      >
         <Navbar />
         <QueryProvider>
          {children}
          </QueryProvider>
      </body>
    </html>
  );
}
